# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.backgroundErrors", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1433750560);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1433750310);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1433750680);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1433750430);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "SG");
user_pref("browser.search.region", "SG");
user_pref("browser.slowStartup.averageTime", 1148);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150525141253");
user_pref("browser.startup.homepage_override.mstone", "38.0.5");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1433836589571");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1433750250540");
user_pref("datareporting.policy.firstRunTime", "1433750189571");
user_pref("datareporting.sessions.current.activeTicks", 28);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 977);
user_pref("datareporting.sessions.current.main", 21);
user_pref("datareporting.sessions.current.sessionRestored", 1163);
user_pref("datareporting.sessions.current.startTime", "1433750189367");
user_pref("datareporting.sessions.current.totalTime", 518);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0.5");
user_pref("extensions.lastAppVersion", "38.0.5");
user_pref("extensions.lastPlatformVersion", "38.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0.5\",\"st\":1433300926000,\"mt\":1433300925000}}}");
user_pref("gecko.buildID", "20150525141253");
user_pref("gecko.mstone", "38.0.5");
user_pref("media.gmp-manager.buildID", "20150525141253");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.backup.ftp", "");
user_pref("network.proxy.backup.ftp_port", 0);
user_pref("network.proxy.backup.socks", "");
user_pref("network.proxy.backup.socks_port", 0);
user_pref("network.proxy.backup.ssl", "");
user_pref("network.proxy.backup.ssl_port", 0);
user_pref("network.proxy.ftp", "127.0.0.1");
user_pref("network.proxy.ftp_port", 9090);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 9090);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9090);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 9090);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1433750189);
user_pref("toolkit.telemetry.previousBuildID", "20150525141253");
